app:
  env: "dev"
  port: "9097"
  version: "1.0.0"

auth:
  jwt_pub: |
    superlongtext
    superlongtext
    superlongtext

db:
  url: "postgres://postgres:postgres@localhost:5432/uploadsvc"

cache:
  url: "redis://default:default@localhost:6379/0"

broker:
  url: "kafka://:@localhost:9092/file-uploaded-topic"
  consumer_group: "cg-fileuploader"
  topic: "file-uploaded-topic"

cdn:
  endpoint: ""
  region: ""
  bucket: ""
  access_key: ""
  secret_key: ""
